steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/mern-app', '.']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/mern-app']

  - name: 'gcr.io/cloud-builders/gcloud'
    args: [
      'run',
      'deploy',
      'mern-app',
      '--image',
      'gcr.io/$PROJECT_ID/mern-app',
      '--region', 'asia-south1', '--platform', 'managed'
    ]
