steps:
  # Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/mern-app', '.']

  # Push the Docker image to Google Container Registry (GCR)
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/mern-app']

images:
  - 'gcr.io/$PROJECT_ID/mern-app'

  # Deploy the container to Google Cloud Run
  # Make sure you've set up Google Cloud Run accordingly
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['run', 'deploy', 'mern-app', '--image', 'gcr.io/$PROJECT_ID/mern-app', '--port', '3000', '--port', '3001', '--port', '5000']

substitutions:
  _APP_PORT: "3000"  # Update with the primary port of your frontend or backend
  _CHAT_PORT: "3001" # Update with the chat service port
  _BACKEND_PORT: "5000" # Update with the backend port
