steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/mern-app', '.']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/mern-app']

  - name: 'gcr.io/cloud-builders/gcloud'
    args: [
      'run',
      'deploy',
      'mern-app',
      '--image',
      'gcr.io/$PROJECT_ID/mern-app',
      '--port=3000',  # Adjust the port as needed
      '--region=asia-south1',  # Specify the region as asia-south1 (Mumbai)
    ]

substitutions:
  _APP_PORT: "3000"   # Update with the primary port of your frontend or backend
  _CHAT_PORT: "3001"  # Update with the chat service port
  _BACKEND_PORT: "5000"  # Update with the backend port
